http:
  routers:
    percens-api:
      rule: Host(`api.percens.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: percens-api

    percens-frontend:
      rule: Host(`percens.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: percens-frontend

  services:
    percens-api:
      loadBalancer:
        servers:
          - url: http://nosignal-survey-backend:8000

    percens-frontend:
      loadBalancer:
        servers:
          - url: http://nosignal-survey-frontend:80
