http:
  routers:
    nosignal-survey-api:
      rule: Host(`api.survey.nosignal.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: nosignal-survey-api

    nosignal-survey-frontend:
      rule: Host(`survey.nosignal.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: nosignal-survey-frontend

  services:
    nosignal-survey-api:
      loadBalancer:
        servers:
          - url: http://nosignal-survey-backend:8000

    nosignal-survey-frontend:
      loadBalancer:
        servers:
          - url: http://nosignal-survey-frontend:80
