entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
