RESULTADO_CUMPLE = "CUMPLE"
RESULTADO_NO_CUMPLE = "NO CUMPLE"

INFORMACION_VIVIENDA_SIN_SERVICIO_ENERGIA = "SIN SERVICIO DE ENERGIA"
INFORMACION_VIVIENDA_IRREGULAR_DIRECTO = "CON SERVICIO IRREGULAR DIRECTO"
INFORMACION_VIVIENDA_IRREGULAR_INDIRECTO = "CON SERVICIO IRREGULAR INDIRECTO"

INFORMACION_VIVIENDA_CUMPLE_CLASIFICACION = (
    INFORMACION_VIVIENDA_SIN_SERVICIO_ENERGIA,
    INFORMACION_VIVIENDA_IRREGULAR_DIRECTO,
    INFORMACION_VIVIENDA_IRREGULAR_INDIRECTO,
)
